include:
  - project: 'kachouei-lab/include-local'
    file: 'x.yml'
    ref: main
    rules:
      - if: '$CI_COMMIT_BRANCH =~ "/^deploy-stg-.*$/'

variables:
  PROJECTNAME: simple-goland-app
  STACKNAME: kachouei
  RUNNER_TAG: "kachouei-laptop"
  
