include:
  - project: 'kachouei-lab/include-local'
    file: 'y.yml'
    ref: main
    name: mutil_env
    variables:
      ABC: mamad

.stg_custome:
  rules:
  - if: '$RUN == "always"'
    when: always
  # build_script:
  # - echo "custome build"

variables:
  PROJECTNAME: simple-goland-app
  STACKNAME: kachouei
  #BUILD_OPT: "--build-arg B1=salam --build-arg B2=by"
  DOCKERFILE_DEV: "Dockerfile"
  PROJECT_PATH: "test/"
  ARGO_PROJECT: default
  HELM_OPT: "--devel"
  #DISABLE_BUILD_IMAGE_STG: "true"
  
