include:
  - project: 'kachouei-lab/include-local'
    file: 'x.yml'
    ref: main

variables:
  PROJECTNAME: simple-goland-app
  STACKNAME: kachouei
  PIPELINE_TRIGGER: "/^deploy-dev-.*$/"
  RUNNER_TAG: "kachouei-laptop"
