include:
  - project: 'kachouei-lab/include-local'
    file: 'x.yml'
    ref: main
    name: mutil_env
    variables:
      ABC: mamad


variables:
  PROJECTNAME: simple-goland-app
  STACKNAME: kachouei
  #BUILD_OPT: "--build-arg B1=salam --build-arg B2=by"
  DOCKERFILE_DEV: "Dockerfile"
  PROJECT_PATH: "test/"
  ARGO_PROJECT: default
  
