include:
  - component: $CI_SERVER_FQDN/DevOPs/cicd/catalog/all-in-one@1
    inputs:
     ENV: stage
     PROJECT_NAME: sga
     STACK_NAME: devops
     DOCKER_CONF: $DOCKER_CONF
     WORKFLOW_ALWAYS: '$CI_COMMIT_BRANCH == "k8s-stg"'
     DEPLOY_WHEN: on_success
  - component: $CI_SERVER_FQDN/DevOPs/cicd/catalog/deploy-trigger@1
    inputs:
     ENV: stage
     PROJECT_NAME: sga
     STACK_NAME: devops
     NS: kachibits
     EXTRA_TAG: v1
     JOB: trigger-deploy Env:Stage kachi-bits/sga

stages:
    - build
    - test
    - sync
    - deploy
    - test-e2e
    - rollback
