include:
  - project: 'DevOPs/Include-ci'
    file: '/helm-ci-stage-alibaba-canary.yml'
  - project: 'DevOPs/Include-ci'
    file: '/helm-ci-stage-alibaba.yml'
devops
stages:
    - release-note
    - build
    - test
    - deploy
    - rollback
    - trigger-ingress
    - rolldown


variables:
    # stage variables
    PROJECTNAME: kachi-beats
    STACKNAME: devops    
    DOCKERFILE_STAGE: Dockerfile
