include:
  - project: 'kachouei-lab/include-local'
    file: 'x.yml'
    ref: main

variables:
  PROJECTNAME: simple-goland-app
  STACKNAME: kachouei
  RUNNER_TAG: "kachouei-laptop"
  
.pipeline_trigger: &pipeline_trigger  
  only:
    - "/^deploy-stg-.*$/"
