include:
  - component: $CI_SERVER_FQDN/DevOPs/cicd/catalog/all-in-one@1
    inputs:
     ENV: staging
     PROJECT_NAME: sga
     STACK_NAME: devops
     DOCKER_CONF: $DOCKER_CONF
     WORKFLOW_ALWAYS: '"mamad"=="mamad"'

