name: build-Deploy stg

on:
  push:
    branches:
      - main
      - staging
jobs:
  staging:
    runs-on: ubuntu-latest
    container:
      image: arm64v8/ubuntu:latest
    permissions:
      id-token: write
      contents: read
    uses: kachi-bits/resuable-actions/.github/workflows/build-deploy-lambda.yml@v1
    with:
      AWS_ACCOUNT_ID: "651706774764"
      AWS_REGION: "me-central-1"
      DOCKERFILE: "Dockerfile.pub"
      BUILD_CONTEXT: "."
      APP_NAME: sga
      PROJECT_NAME: kachibits
      CLUSTER_NAME: stg
