name: build-Deploy dev

on:
  push:
    branches:
      - main
jobs:
  api:
    permissions:
      id-token: write
      contents: read
    uses: kachi-bits/resuable-actions/.github/workflows/build-deploy-lambda.yml@main
    with:
      AWS_ACCOUNT_ID: "575108942639"
      AWS_REGION: "me-central-1"
      LAMBDA_NAME: "kachi-bits-c2-sga-dev"
      ECR_REPOSITORY: "kachi-bits/sga-dev"
      DOCKERFILE: "Dockerfile.pub"
      BUILD_CONTEXT: "."

